version: '2'
services:
  server1: 
    image: jetmeng/centos_ansible:7
    container_name: server1
    ports:
      - "32110:22"
    restart: always
  server2: 
    image: jetmeng/centos_ansible:7
    container_name: server2
    depends_on:
      - server1
    ports:
      - "32111:22"
    restart: always
  server3: 
    image: jetmeng/centos_ansible:7
    container_name: server3
    depends_on:
      - server2
    ports:
      - "32112:22"
    restart: always
