---
- hosts: db
  user: docker
  become: true 
  vars_files:
    - vars.yml
  tasks:
    - name: download epel-release
      yum:
        name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
        state: present
    - name: install mysql
      yum:
        name: ['mysql-community-devel*', 'mysql-community-server*', 'MySQL-python']
        state: present
    - name: copy my.cnf
      copy:
        src: /Users/megao/Downloads/go_src/github.com/ansible-to-docker-host/my.cnf
        dest: /etc/my.cnf
        mode: 0644
    - name: enable mysql
      systemd:
        name: mysqld
        state: restarted
        enabled: yes
    - name: get root password
      shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk -F ' ' '{print $(NF)}'"
      register: root_password
    - name: update expired root user password
      command: mysql --user root --password={{ root_password.stdout }} --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql.root.password }}';"
    - name: create mysql client user
      mysql_user:
        login_user: root
        login_password: "{{ mysql.root.password }}"
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        priv: '*.*:ALL,GRANT'
        state: present
        host: '%'
      with_items:
        - "{{ mysql.users }}"
